# Generated by Django 4.1.7 on 2023-04-08 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(null=True)),
                ('image', models.ImageField(upload_to='images/skills')),
                ('perc', models.IntegerField()),
            ],
        ),
    ]
